name: build-deploy-worforce-api-dev
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "infra/*"

  workflow_dispatch:

env:
  AZURE_CORE_OUTPUT: "none"
  resourceGroupName: rg-bfwworkforceservices-dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy-apps-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Find Azure Container Registry in Resource Group
        id: queryAcr
        run: |
          echo "acrLoginServer=$(az acr list --resource-group ${{ env.resourceGroupName }} --query '[0].loginServer' --output tsv)" >> "$GITHUB_ENV"

      - name: Log in to Azure Container Registry
        run: |
          docker login ${{ env.acrLoginServer }}.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $(az acr login --name workforceservicesacrdev.azurecr.io --expose-token --only-show-errors --query 'accessToken' --output tsv)

      - name: Find Managed Identity in Resource Group
        run: |
          echo "managedIdentityId=$(az identity list --resource-group ${{ env.resourceGroupName }} --query '[0].id' --output tsv)" >> "$GITHUB_ENV"

#az acr login --name workforceservicesacrdev.azurecr.io --expose-token --only-show-errors --query 'accessToken' --output tsv
#docker login loginServer -u 00000000-0000-0000-0000-000000000000 -p accessToken

# - name: Log in to Azure Container Registry
#   uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
#   with:
#     registry: workforceservicesacrdev.azurecr.io
#     username: ${{ secrets.AZURE_CLIENT_ID }}
#     password: ${{ secrets.TODO }}

# - name: Build and deploy to dev
#   uses: azure/container-apps-deploy-action@5f5f4c56ca90376e3cfbd76ba8fe8533c784e655
#   with:
#     appSourcePath: ${{ github.workspace }}
#     acrName: workforceservicesacrdev
#     containerAppName: workforce-api
#     resourceGroup: ${{ env.resourceGroupName }}
