name: build-deploy-workforce-api-dev
on:
  push:
    branches:
      - "main"
    paths:
      - "wfapi/**"
      - "!infra/**"
      - "infra/workforce-api-aca/**"
      - "!.github/workflows/**"
      - ".github/workflows/build-deploy-workforce-api-dev.yml"

  workflow_dispatch:

env:
  AZURE_CORE_OUTPUT: "none"
  resourceGroupName: "rg-bfwworkforceservices-dev"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-apps-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Find Azure Container Registry in Resource Group
        id: queryAcr
        run: |
          echo "acrLoginServer=$(az acr list --resource-group ${{ env.resourceGroupName }} --query '[0].loginServer' --output tsv)" >> "$GITHUB_ENV"

      - name: Log in to Azure Container Registry
        run: |
          docker login $acrLoginServer -u 00000000-0000-0000-0000-000000000000 -p $(az acr login --name $acrLoginServer --expose-token --only-show-errors --query 'accessToken' --output tsv)

      - name: Determine the container image tag
        id: tag
        run: echo "containerImage=$acrLoginServer/workforce-api:${{ github.run_number }}" >> "$GITHUB_ENV"

      - name: Build and push container image
        working-directory: ./wfapi
        run: |
          docker build -t ${{ env.containerImage }} .
          docker push ${{ env.containerImage }}

      - name: Provision workforce-api azure container app
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resourceGroupName }}
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/workforce-api-aca/workforce-api-aca.bicep
          parameters: >-
            containerImage=${{ env.containerImage }}
            resourceUniqueNameElement=8db7e8c
            environmentName=dev
            appAadClientId=${{ secrets.APP_AAD_CLIENT_ID_DEV }}
            appAadClientSecret=${{ secrets.APP_AAD_CLIENT_SECRET_DEV }}
            appAadTenantId=${{ secrets.APP_AAD_TENANT_ID_DEV }}
            graphTenantId=${{ secrets.GRAPH_TENANT_ID_DEV }}
            graphClientId=${{ secrets.GRAPH_CLIENT_ID_DEV }}
            graphClientSecret=${{ secrets.GRAPH_CLIENT_SECRET_DEV }}
            workforceSiteHostname=${{ secrets.WORKFORCE_SITE_HOSTNAME_DEV }}
            workforceSitePath=${{ secrets.WORKFORCE_SITE_PATH_DEV }}
            workforceProfilesListGuid=${{ vars.WORKFORCE_PROFILES_LIST_GUID_DEV }}
            workforceLoginsListGuid=${{ vars.WORKFORCE_LOGINS_LIST_GUID_DEV }}
            wfApplicationsListGuid=${{ vars.WORKFORCE_APPLICATIONS_LIST_GUID_DEV }}
            wfTemplatesListGuid=${{ vars.WORKFORCE_TEMPLATES_LIST_GUID_DEV }}
            wfPhotosServiceBaseUrl=${{ vars.WORKFORCE_PHOTOS_SERVICE_BASE_URL_DEV }}
