name: build-deploy-worforce-api-dev
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "infra/**"
      - "!infra/workforce-api/**"
      - ".github/workflows/**"
      - "!.github/workflows/build-deploy-worforce-api-dev.yml"

  workflow_dispatch:

env:
  AZURE_CORE_OUTPUT: "none"
  resourceGroupName: "rg-bfwworkforceservices-dev"
  RESOURCE_SUFFIX: "8db7e8c"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-apps-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Find Azure Container Registry in Resource Group
        id: queryAcr
        run: |
          echo "acrLoginServer=$(az acr list --resource-group ${{ env.resourceGroupName }} --query '[0].loginServer' --output tsv)" >> "$GITHUB_ENV"

      - name: Log in to Azure Container Registry
        run: |
          docker login $acrLoginServer -u 00000000-0000-0000-0000-000000000000 -p $(az acr login --name $acrLoginServer --expose-token --only-show-errors --query 'accessToken' --output tsv)

      - name: Build and push container image
        run: |
          docker build -t $acrLoginServer/workforce-api:latest .
          docker push $acrLoginServer/workforce-api:latest
          echo "CONTAINER_IMAGE=$acrLoginServer/workforce-api:latest" >> "$GITHUB_ENV"

      - name: Provision workforce-api azure container app
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resourceGroupName }}
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/workforce-api-aca/workforce-api-aca.bicep
          parameters: ${{ github.workspace }}/infra/workforce-api-aca/parameters/dev.bicepparam
