name: provision-azure-container-apps-dev
on:
  push:
    branches:
      - "main"
    paths:
      - "infra/main.bicep"
      - "infra/parameters/dev.bicepparam"
      - "infra/modules/*"

  workflow_dispatch:

env:
  AZURE_CORE_OUTPUT: "none"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-apps-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to dev
        uses: azure/arm-deploy@a1361c2c2cd398621955b16ca32e01c65ea340f5
        with:
          resourceGroup: rg-bfwworkforceservices-dev
          deploymentName: ${{ github.run_number }}
          template: ${{ github.workspace }}/infra/main.bicep
          parameters: ${{ github.workspace }}/infra/parameters/dev.bicepparam
